name: esewa_client
description: A flutter plugin to integrate ESEWA merchant services into your application.
version: 0.1.1
homepage: https://github.com/sanzaal/esewa_client_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sanzaaltech.esewa_client
        pluginClass: EsewaClientPlugin
      ios:
        pluginClass: EsewaClientPlugin

